In [18]:
import numpy as np

In [17]:
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3],[4,5,6,7]])

In [63]:
np.dot(A,B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [75]:
matrix_result = np.dot(A, B)
print(result)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [74]:
print(matrix_result.max())

47
